### ISSUE TITLE
Adapter bleibt rot und funktioniert nicht

### ISSUE THREAD

**Issue by severendis** [MadErstam/ioBroker.controme#28]
**Describe the bug**  
Der Adapter startet nicht. Er bleibt auf ROT stehen. Im LOG werden Fehler ausgegeben.
Die Zugangsdaten zum MINI Server sind eingegeben. Die API ist aktiv.

**To Reproduce**  
Der Fehler tritt immer auf. Nach Neuinstallation des Adapters.

**Expected behavior**  
Das der Adapter mir Werte ausließt und in die Objekte schreibt.

**Screenshots & Logfiles**  
`
2022-05-19 22:38:20.543 - info: host.iobroker instance system.adapter.controme.0 started with pid 7889
--
2022-05-19 22:38:22.375 - error: host.iobroker Caught by controller[0]: internal/modules/cjs/loader.js:1102
2022-05-19 22:38:22.375 - error: host.iobroker Caught by controller[0]: throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
2022-05-19 22:38:22.375 - error: host.iobroker Caught by controller[0]: ^
2022-05-19 22:38:22.375 - error: host.iobroker Caught by controller[0]: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /opt/iobroker/node_modules/iobroker.controme/node_modules/got/dist/source/index.js
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: require() of ES modules is not supported.
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: require() of /opt/iobroker/node_modules/iobroker.controme/node_modules/got/dist/source/index.js from /opt/iobroker/node_modules/iobroker.controme/main.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /opt/iobroker/node_modules/iobroker.controme/node_modules/got/package.json.
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: at new NodeError (internal/errors.js:322:7)
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19)
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: at require (internal/modules/cjs/helpers.js:101:18)
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.controme/main.js:12:13)
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1085:14)
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2022-05-19 22:38:22.376 - error: host.iobroker Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32) {
2022-05-19 22:38:22.377 - error: host.iobroker Caught by controller[0]: code: 'ERR_REQUIRE_ESM'
2022-05-19 22:38:22.377 - error: host.iobroker Caught by controller[0]: }
2022-05-19 22:38:22.377 - error: host.iobroker instance system.adapter.controme.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2022-05-19 22:38:22.377 - info: host.iobroker Restart adapter system.adapter.controme.0 because enabled
`

**Versions:**  
 - Adapter version: 0.3.0 (Installiert wurde Version 0.3.4-alpha.1, wird aber nicht angezeigt)
 - JS-Controller version: 4.0.23
 - Node version: 14.19.1
 - Operating system: Ubuntu 20.04.4 LTS

**Additional context**  
Vielen Dank!

**Comment by MadErstam** [comment]
Hi!

Das war ein Bug in den Dependencies, sollte jetzt gefixed sein. Teste mal bitte!

Viele Grüße!

Marc

**Comment by severendis** [comment]
Hallo Marc!

Danke erst mal. Ich brauche aber Hilfe. Wie kann ich diese alpha Version installieren?

Vielen Dank!

Uwe
